#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mathematician.Droid.Resource", IsApplication=true)]

namespace Mathematician.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mathematician.Common.Resource.Attribute.camera_id = global::Mathematician.Droid.Resource.Attribute.camera_id;
			global::Mathematician.Common.Resource.Attribute.show_fps = global::Mathematician.Droid.Resource.Attribute.show_fps;
			global::Mathematician.Common.Resource.Id.any = global::Mathematician.Droid.Resource.Id.any;
			global::Mathematician.Common.Resource.Id.back = global::Mathematician.Droid.Resource.Id.back;
			global::Mathematician.Common.Resource.Id.front = global::Mathematician.Droid.Resource.Id.front;
			global::Mathematician.Common.Resource.String.ApplicationName = global::Mathematician.Droid.Resource.String.ApplicationName;
			global::Mathematician.Common.Resource.String.Hello = global::Mathematician.Droid.Resource.String.Hello;
			global::Mathematician.Common.Resource.Styleable.CameraBridgeViewBase = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase;
			global::Mathematician.Common.Resource.Styleable.CameraBridgeViewBase_camera_id = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase_camera_id;
			global::Mathematician.Common.Resource.Styleable.CameraBridgeViewBase_show_fps = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase_show_fps;
			global::Mathematician.Vision.Resource.Attribute.camera_id = global::Mathematician.Droid.Resource.Attribute.camera_id;
			global::Mathematician.Vision.Resource.Attribute.show_fps = global::Mathematician.Droid.Resource.Attribute.show_fps;
			global::Mathematician.Vision.Resource.Id.any = global::Mathematician.Droid.Resource.Id.any;
			global::Mathematician.Vision.Resource.Id.back = global::Mathematician.Droid.Resource.Id.back;
			global::Mathematician.Vision.Resource.Id.front = global::Mathematician.Droid.Resource.Id.front;
			global::Mathematician.Vision.Resource.String.ApplicationName = global::Mathematician.Droid.Resource.String.ApplicationName;
			global::Mathematician.Vision.Resource.String.Hello = global::Mathematician.Droid.Resource.String.Hello;
			global::Mathematician.Vision.Resource.Styleable.CameraBridgeViewBase = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase;
			global::Mathematician.Vision.Resource.Styleable.CameraBridgeViewBase_camera_id = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase_camera_id;
			global::Mathematician.Vision.Resource.Styleable.CameraBridgeViewBase_show_fps = global::Mathematician.Droid.Resource.Styleable.CameraBridgeViewBase_show_fps;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int camera_id = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int show_fps = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int CaptureButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int FeedResult = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int PodList = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int ResultHeader = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int SelectButton = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int SolveButton = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int TextArea = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int any = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int apod = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int back = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int front = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int podContent = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int podTitle = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int pod = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Text = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Capture = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int Description = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int ExtractedText = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int NoCameraApp = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int Result = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int Select = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int SelectPicture = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int Solve = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int WikiQueryError = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
